node_lines:
  - node_line_name: retrieve_node_line
    nodes:
      - node_type: retrieval
        strategy:
          metrics: [ retrieval_f1, retrieval_recall, retrieval_precision ]
        top_k: 3
        modules:
          - module_type: bm25
  - node_line_name: generate_node_line
    nodes:
      - node_type: prompt_maker
        strategy:
          metrics: [ bleu, meteor, rouge, sem_score ]
        modules:
          - module_type: fstring
            prompt: "Read the passages and answer the given question. \n Question: {query} \n Passage: {retrieved_contents} \n Answer : "
      - node_type: generator
        strategy:
          metrics: [ bleu, meteor, rouge, sem_score ]
        modules:
        - module_type: llama_index_llm
          llm: vllm
          model: [ meta-llama/Llama-2-7b-chat-hf, mistralai/Mistral-7B-Instruct-v0.2 ]
          batch: 8
        - module_type: llama_index_llm
          llm: openai
          model: gpt-3.5-turbo-0125
          batch: 2
